### ISSUE TITLE
Error 403 when using get_notes_folders()

### ISSUE THREAD

**Issue by Felina-Lain** [neighbordog/deviantart#11]
Hello, I'm trying to do a small app to backup all my da notes
I managed to get the token and auth, using the exemple codes, I get a link, which I use to get a code, and when I input the code, I get my username returned. So I thought it was working fine?

But when I tried to use get_notes_folders, I get this error:

```
Traceback (most recent call last):
  File "********\AppData\Local\Programs\Python\Python39\lib\site-packages\deviantart\api.py", line 1730, in _req     
    response = self.oauth.request(request_parameter, data=encdata)
  File "********\AppData\Local\Programs\Python\Python39\lib\site-packages\sanction\__init__.py", line 166, in request
    resp = urlopen(req)
  File "********l\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "********\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "********\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "********\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "********\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "********\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "********\Desktop\DA note downloader.py", line 42, in <module>
    notefolders = da.get_notes_folders()
  File "********\AppData\Local\Programs\Python\Python39\lib\site-packages\deviantart\api.py", line 1653, in get_notes_folders
    response = self._req('/notes/folders')
  File "********\AppData\Local\Programs\Python\Python39\lib\site-packages\deviantart\api.py", line 1733, in _req
    raise DeviantartError(e)
deviantart.api.DeviantartError: HTTP Error 403: Forbidden
```

Here is the code with what I added at the end:
```
if da.access_token:

    print ("The access token {}.".format(da.access_token))
    print ("The refresh token {}.".format(da.refresh_token))

    #the User object of the authorized user
    user = da.get_user()

    print ("The name of the authorized user is {}.".format(user.username))
    
    
    notefolders = da.get_notes_folders()
    for folders in notefolders:
        print(folders.folder & folders.title)
```

I'm not quite sure what I did wrong?

**Comment by Felina-Lain** [comment]
Edit: I found this, https://www.deviantart.com/developers/errors#:~:text=If%20you%20recieve%20403%20errors,requests%20not%20meeting%20this%20requirement.
Might be it, but I dunno what to do with that info
